### ISSUE TITLE
Work In Progress?

### ISSUE THREAD

**Issue by danielzen** [SteveRidout/banana-split#1]
Hey Steve,
  Thank you for working on this code. One of the projects I am working on is looking for a simple AB test framework that stores results in Mongo. We found your code, but can see that it is a work in progress. I was hoping that before we put any time into it, you could tell us if it was in a condition for us to start working with it?

Thanks,
Daniel

**Comment by SteveRidout** [comment]
Hi Daniel,

It depends on your expectations, if you're happy to use this knowing that
it's very immature then I'm very happy to receive your feedback, bug
reports, review pull requests, etc...

I'm using it in production on http://readlang.com and it's working well so
far. The main problem at the moment is that getResult() in Banana.js does
some aggregation which will get very expensive as the number of
participants and events grows, I need to think about how to scale this
efficiently.

Thanks for showing interest in using it, I'll write some documentation and
clean up the code tomorrow so that you'll have an easier start if you
decide to use it.

Steve

**Comment by danielzen** [comment]
Steve,
  That's exactly the type of information we needed:

1.  You are using it in production
2.  That we should be careful because it is not ready to scale.

Any sort of documentation would be appreciated, and we would make sure to report bugs and make pull requests if we have anything to add...

Thanks again,
Daniel

**Comment by danielzen** [comment]
Thank you so much for the new documentation!
Much appreciated.
